### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by TheGnarpy** [Zunkz/furrestmodpack#2]
Rtx 3050
16 gb of ram
11th gen core i5-11400h

https://mclo.gs/1yhvkbN

**Comment by Zunkz** [comment]
Are you using a shaderpack that is not included in the Modpack by default?

**Comment by TheGnarpy** [comment]
No

**Comment by Zunkz** [comment]
Have you tried *fully* uninstalling the pack and installing it again?

**Comment by Zunkz** [comment]
Issue fixed
